# ------ #
# Author: Valentina Gomez
# Maintainers: Valentina Gomez
# Date: Oct 21, 2021:
# License: 
# ------ #

#------------------------Prompt colors------------- ----- #
PS1="\n\[\e[38;5;125m\]\u\[\e[0;33m\] at \[\e[38;5;63m\]\h\[\e[0;33m\]:\[\e[38;5;80m\]\w\[\e[0;37m\]\n \[\e[0;33m\]$ \[\e[0;00m\]"
